/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.TemaDao;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Color;
import java.awt.FlowLayout;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author U53R
 */
public class ContentGui extends javax.swing.JFrame {
    
    private static String usuario;

    /**
     * Creates new form Content
     */
    public ContentGui(String usuario) {
        initComponents();
        if (usuario.equals("PROFESOR")) {
            prevButton.setBackground(new java.awt.Color(105, 151, 207));
            prevButton.setForeground(new java.awt.Color(255, 255, 251));
            prevButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            prevButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            prevLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18)); // NOI18N
            prevLabel.setForeground(new java.awt.Color(255, 255, 251));
            prevLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            prevLabel.setText("Atrás");
            prevButton.add(prevLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

            jPanel1.add(prevButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 120, 47));
        }
        
        this.usuario = usuario;
        cargarBotonesDesdeDAO();
    }

    private void cargarBotonesDesdeDAO() {
        TemaDao dao = new TemaDao();
        ArrayList<String> nombresTemas = dao.obtenerNombresBotones();

        JPanel panelContenedor = new JPanel();
        panelContenedor.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10));  // Alineado a la izquierda con espacio de 10 píxeles

        for (String nombre : nombresTemas) {
            JPanel panelTema = new JPanel();
            panelTema.setBackground(new java.awt.Color(105, 151, 207));
            panelTema.setForeground(new java.awt.Color(255, 255, 251));
            panelTema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

            JLabel labelNombre = new JLabel();
            labelNombre.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18));
            labelNombre.setForeground(new java.awt.Color(255, 255, 251));
            labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelNombre.setText(nombre);

            panelTema.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    // Implementa el manejo del clic según tus necesidades
                    new TopicGui(nombre, usuario).setVisible(true);
                    ContentGui.this.dispose();
                }
            });

            panelTema.setLayout(new BorderLayout());
            panelTema.add(labelNombre, BorderLayout.CENTER);

            // Establece el tamaño del panel de tema
            panelTema.setPreferredSize(new Dimension(240, 47));

            // Agrega el panel al panel contenedor
            panelContenedor.add(panelTema);
        }

        // Establece el tamaño preferido del panel contenedor
        panelContenedor.setPreferredSize(new Dimension(500, (nombresTemas.size() / 2 + 1) * 57)); // 57 = 47 (tamaño del panel) + 10 (espacio entre filas)

        jScrollPane1.setViewportView(panelContenedor);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        closeSessionLabel = new javax.swing.JLabel();
        profileLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        prevButton = new javax.swing.JPanel();
        prevLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        circlesBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Academy");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(239, 246, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Rounded Mplus 1c ExtraBold", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(119, 149, 203));
        jLabel3.setText("Contenido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        closeSessionLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        closeSessionLabel.setForeground(new java.awt.Color(105, 151, 207));
        closeSessionLabel.setText("Cerrar Sesión");
        closeSessionLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeSessionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeSessionLabelMouseClicked(evt);
            }
        });
        jPanel1.add(closeSessionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        profileLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        profileLabel.setForeground(new java.awt.Color(105, 151, 207));
        profileLabel.setText("Mi Cuenta");
        profileLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileLabelMouseClicked(evt);
            }
        });
        jPanel1.add(profileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, -1, -1));

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N
        jPanel1.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, -1, 60));

        prevButton.setBackground(new java.awt.Color(239, 246, 249));
        prevButton.setForeground(new java.awt.Color(255, 255, 251));
        prevButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        prevButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prevButtonMouseClicked(evt);
            }
        });
        prevButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prevLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18)); // NOI18N
        prevLabel.setForeground(new java.awt.Color(255, 255, 251));
        prevLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prevButton.add(prevLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jPanel1.add(prevButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 120, 47));

        jScrollPane1.setBackground(new java.awt.Color(239, 246, 249));
        jScrollPane1.setForeground(new java.awt.Color(239, 246, 249));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(true);
        jScrollPane1.getViewport().setOpaque(true);
        jScrollPane1.getViewport().setBackground(new Color(239, 246, 249));
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 520, 260));

        circlesBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgContent.png"))); // NOI18N
        jPanel1.add(circlesBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void closeSessionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeSessionLabelMouseClicked
        // TODO add your handling code here:
        new LoginGui().setVisible(true);   // Crea y muestra el login
        this.dispose();                   // Cierra la ventana actual
    }//GEN-LAST:event_closeSessionLabelMouseClicked

    private void profileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileLabelMouseClicked
        // TODO add your handling code here:
        new ProfileGui(usuario).setVisible(true);   // Instancia la clase ProfileGui y llama a setVisible(true) para hacerse visible
        this.dispose();                     // Cierra la ventana actual en la que se hace clic
    }//GEN-LAST:event_profileLabelMouseClicked

    private void prevButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevButtonMouseClicked
        // TODO add your handling code here:
        if (usuario.equals("PROFESOR")) {
            new OptionsGui(usuario).setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_prevButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContentGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContentGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContentGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContentGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContentGui(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel circlesBg;
    private javax.swing.JLabel closeSessionLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel prevButton;
    private javax.swing.JLabel prevLabel;
    private javax.swing.JLabel profileLabel;
    // End of variables declaration//GEN-END:variables
}
