/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.Student;
import dao.EstudianteDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author U53R
 */
public class SignUpGui extends javax.swing.JFrame {
    List<Student> usuarios = new ArrayList<Student>();

    /**
     * Creates new form SignUp
     */
    public SignUpGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        signUpLabel = new javax.swing.JLabel();
        userInput = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        psswdLabel = new javax.swing.JLabel();
        psswdInput = new javax.swing.JPasswordField();
        rePsswdInput = new javax.swing.JPasswordField();
        nextButton = new javax.swing.JPanel();
        nextLabel = new javax.swing.JLabel();
        rePsswdLabel = new javax.swing.JLabel();
        logIn = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        lastNameInput = new javax.swing.JTextField();
        circleBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(239, 246, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUpLabel.setFont(new java.awt.Font("Rounded Mplus 1c ExtraBold", 1, 48)); // NOI18N
        signUpLabel.setForeground(new java.awt.Color(119, 149, 203));
        signUpLabel.setText("Registro");
        jPanel1.add(signUpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        userInput.setBackground(new java.awt.Color(105, 151, 207));
        userInput.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        userInput.setForeground(new java.awt.Color(255, 255, 251));
        userInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userInput.setBorder(null);
        userInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInputActionPerformed(evt);
            }
        });
        userInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userInputKeyPressed(evt);
            }
        });
        jPanel1.add(userInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 220, 33));

        userLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(24, 49, 85));
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText("Usuario");
        jPanel1.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 150, 220, -1));

        emailInput.setBackground(new java.awt.Color(105, 151, 207));
        emailInput.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        emailInput.setForeground(new java.awt.Color(255, 255, 251));
        emailInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailInput.setBorder(null);
        jPanel1.add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 220, 33));

        emailLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(24, 49, 85));
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLabel.setText("Correo Electrónico");
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 230, 210, -1));

        psswdLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18)); // NOI18N
        psswdLabel.setForeground(new java.awt.Color(24, 49, 85));
        psswdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        psswdLabel.setText("Contraseña");
        jPanel1.add(psswdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 220, -1));

        psswdInput.setBackground(new java.awt.Color(105, 151, 207));
        psswdInput.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        psswdInput.setForeground(new java.awt.Color(255, 255, 251));
        psswdInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        psswdInput.setBorder(null);
        psswdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psswdInputActionPerformed(evt);
            }
        });
        jPanel1.add(psswdInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 220, 33));

        rePsswdInput.setBackground(new java.awt.Color(105, 151, 207));
        rePsswdInput.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        rePsswdInput.setForeground(new java.awt.Color(255, 255, 251));
        rePsswdInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rePsswdInput.setBorder(null);
        rePsswdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rePsswdInputActionPerformed(evt);
            }
        });
        jPanel1.add(rePsswdInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 220, 33));

        nextButton.setBackground(new java.awt.Color(105, 151, 207));
        nextButton.setForeground(new java.awt.Color(255, 255, 251));
        nextButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonMouseClicked(evt);
            }
        });
        nextButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nextLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18)); // NOI18N
        nextLabel.setForeground(new java.awt.Color(255, 255, 251));
        nextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextLabel.setText("Registrar");
        nextButton.add(nextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, 120, 30));

        jPanel1.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 130, 47));

        rePsswdLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18)); // NOI18N
        rePsswdLabel.setForeground(new java.awt.Color(24, 49, 85));
        rePsswdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rePsswdLabel.setText("Confirmar Contraseña");
        jPanel1.add(rePsswdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 220, -1));

        logIn.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        logIn.setForeground(new java.awt.Color(105, 151, 207));
        logIn.setText("Iniciar Sesión");
        logIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logInMouseClicked(evt);
            }
        });
        jPanel1.add(logIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N
        jPanel1.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, -1, 60));

        nameInput.setBackground(new java.awt.Color(105, 151, 207));
        nameInput.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        nameInput.setForeground(new java.awt.Color(255, 255, 251));
        nameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameInput.setBorder(null);
        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });
        nameInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameInputKeyPressed(evt);
            }
        });
        jPanel1.add(nameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 220, 33));

        nameLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(24, 49, 85));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Nombre");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 150, 210, -1));

        lastNameLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(24, 49, 85));
        lastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastNameLabel.setText("Apellido");
        jPanel1.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 220, -1));

        lastNameInput.setBackground(new java.awt.Color(105, 151, 207));
        lastNameInput.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        lastNameInput.setForeground(new java.awt.Color(255, 255, 251));
        lastNameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastNameInput.setBorder(null);
        lastNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameInputActionPerformed(evt);
            }
        });
        lastNameInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lastNameInputKeyPressed(evt);
            }
        });
        jPanel1.add(lastNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 220, 33));

        circleBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgSignUp.png"))); // NOI18N
        jPanel1.add(circleBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 890, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void psswdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psswdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psswdInputActionPerformed

    private void rePsswdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rePsswdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rePsswdInputActionPerformed

    private void logInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInMouseClicked
        // TODO add your handling code here:
        new LoginGui().setVisible(true);   // Instancia la clase SingUp y llama a setVisible(true) para hacerse visible
        this.dispose();                   // Cierra la ventana actual en la que se hace clic
    }//GEN-LAST:event_logInMouseClicked

    // Método para el botón registrar
    private void nextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseClicked
        // Valida que los campos esten ingresados
        if(userInput.getText().isBlank() || String.valueOf(psswdInput.getPassword()).isBlank() || String.valueOf(rePsswdInput.getPassword()).isBlank()  || emailInput.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Todos los datos deben ser ingresados.");
        } else if(userInput.getText().length() < 2 || userInput.getText().length() > 10) {  // Valida que el usuario este entre 2 y 9 de tamaño
            JOptionPane.showMessageDialog(this, "El usuario debe tener un tamaños de entre 2 y 9 caracteres.");
        } else if(String.valueOf(psswdInput.getPassword()).length() < 8) {  // Valida que la contraseña tenga mínimo 8 caracteres
            JOptionPane.showMessageDialog(this, "La contraseña debe contener por mínimo 8 caracteres.");
        } else if(!String.valueOf(psswdInput.getPassword()).equals(String.valueOf(rePsswdInput.getPassword()))) {   // Valida que la contraseña esté bien escrita
            JOptionPane.showMessageDialog(this, "Las contraseñas no son iguales.");
        } else {    // En caso de que todos los campos estén correctos
            
            
            Student estudiante = new Student(this.userInput.getText(), this.nameInput.getText(), this.lastNameInput.getText(), String.valueOf(this.psswdInput.getPassword()), this.emailInput.getText());
            EstudianteDao dao = new EstudianteDao();
            if(dao.agregar(estudiante) != 1) {
                // Limpiar campos
                userInput.setText("");
                nameInput.setText("");
                lastNameInput.setText("");
                emailInput.setText("");
                psswdInput.setText("");
                rePsswdInput.setText("");
                
                
                dao.insertarUsuarioEnDB();
            }
            
            
        }
        

    }//GEN-LAST:event_nextButtonMouseClicked

    private void userInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userInputKeyPressed
        // TODO add your handling code here:
        /*char c = evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            userInput.setEditable(true);
        } else {
            userInput.setEditable(false);
        }*/
    }//GEN-LAST:event_userInputKeyPressed

    private void userInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userInputActionPerformed

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputActionPerformed

    private void nameInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameInputKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputKeyPressed

    private void lastNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameInputActionPerformed

    private void lastNameInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameInputKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameInputKeyPressed

    public JTextField getEmailInput() {
        return emailInput;
    }

    public JPasswordField getPsswdInput() {
        return psswdInput;
    }

    public JPasswordField getRePsswdInput() {
        return rePsswdInput;
    }

    public JTextField getUserInput() {
        return userInput;
    }

    public JTextField getLastNameInput() {
        return lastNameInput;
    }

    public JTextField getNameInput() {
        return nameInput;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel circleBg;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel logIn;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel nextButton;
    private javax.swing.JLabel nextLabel;
    private javax.swing.JPasswordField psswdInput;
    private javax.swing.JLabel psswdLabel;
    private javax.swing.JPasswordField rePsswdInput;
    private javax.swing.JLabel rePsswdLabel;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JTextField userInput;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
