/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.TemaDao;
import javax.swing.JOptionPane;

/**
 *
 * @author U53R
 */
public class TopicGui extends javax.swing.JFrame {
    private static String nombre, usuario;
    
    /**
     * Creates new form Topic
     */
    public TopicGui(String nombre, String usuario) {
        initComponents();
        
        if (usuario.equals("PROFESOR")) {
            jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-10-32.png"))); // NOI18N
            jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-2-32.png"))); // NOI18N
            jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, -1));

            titleText.setEditable(true);
            titleText.setFocusable(true);
            
            jTextArea1.setEditable(true);
            jTextArea1.setFocusable(true);
        }
        
        this.nombre = nombre;
        this.usuario = usuario;
        titleText.setText(nombre);
        jTextArea1.setText(new TemaDao().obtenerContenidoTema(nombre));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        closeSessionLabel = new javax.swing.JLabel();
        profileLabel = new javax.swing.JLabel();
        prevButton = new javax.swing.JPanel();
        prevLabel = new javax.swing.JLabel();
        circlesBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Academy");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(239, 246, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleText.setEditable(false);
        titleText.setBackground(new java.awt.Color(239, 246, 249));
        titleText.setFont(new java.awt.Font("Rounded Mplus 1c ExtraBold", 1, 48)); // NOI18N
        titleText.setForeground(new java.awt.Color(119, 149, 203));
        titleText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        titleText.setText("Nombre del Tema");
        titleText.setBorder(null);
        titleText.setFocusable(false);
        jPanel1.add(titleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 540, -1));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, -1));

        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N
        jPanel1.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, -1, 60));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(true);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(171, 225, 248));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(24, 49, 85));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Contenido");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 840, 270));

        closeSessionLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        closeSessionLabel.setForeground(new java.awt.Color(105, 151, 207));
        closeSessionLabel.setText("Cerrar Sesión");
        closeSessionLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeSessionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeSessionLabelMouseClicked(evt);
            }
        });
        jPanel1.add(closeSessionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        profileLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        profileLabel.setForeground(new java.awt.Color(105, 151, 207));
        profileLabel.setText("Mi Cuenta");
        profileLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileLabelMouseClicked(evt);
            }
        });
        jPanel1.add(profileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        prevButton.setBackground(new java.awt.Color(105, 151, 207));
        prevButton.setForeground(new java.awt.Color(255, 255, 251));
        prevButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prevButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prevButtonMouseClicked(evt);
            }
        });
        prevButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prevLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18)); // NOI18N
        prevLabel.setForeground(new java.awt.Color(255, 255, 251));
        prevLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prevLabel.setText("Volver");
        prevButton.add(prevLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jPanel1.add(prevButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 120, 47));

        circlesBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgTopic.png"))); // NOI18N
        jPanel1.add(circlesBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeSessionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeSessionLabelMouseClicked
        // TODO add your handling code here:
        new LoginGui().setVisible(true);   // Crea y muestra el login
        this.dispose();                   // Cierra la ventana actual
    }//GEN-LAST:event_closeSessionLabelMouseClicked

    private void profileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileLabelMouseClicked
        // TODO add your handling code here:
        new ProfileGui(usuario).setVisible(true);   // Instancia la clase ProfileGui y llama a setVisible(true) para hacerse visible
        this.dispose();                     // Cierra la ventana actual en la que se hace clic
    }//GEN-LAST:event_profileLabelMouseClicked

    private void prevButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevButtonMouseClicked
        // TODO add your handling code here:
        new ContentGui(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prevButtonMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        if (usuario.equals("PROFESOR")) {
            int sw = new TemaDao().borrarTema(nombre);
            if (sw != 0) {
                new OptionsGui(usuario).setVisible(true);
                this.dispose();
            } 
        }
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if (usuario.equals("PROFESOR")) {
            new TemaDao().actualizarContenido(nombre, this.jTextArea1.getText());
            
            new TemaDao().actualizarTitulo(nombre, this.titleText.getText());
            JOptionPane.showMessageDialog(this, "Tema actualizado exitosamente.");
        }
        
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TopicGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TopicGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TopicGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TopicGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TopicGui(nombre, usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel circlesBg;
    private javax.swing.JLabel closeSessionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel prevButton;
    private javax.swing.JLabel prevLabel;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JTextField titleText;
    // End of variables declaration//GEN-END:variables
}
