/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package academy;

/**
 *
 * @author U53R
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userInput = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        psswdLabel = new javax.swing.JLabel();
        psswdInput = new javax.swing.JPasswordField();
        rePsswdInput = new javax.swing.JPasswordField();
        rePsswdLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        logIn = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userInput.setBackground(new java.awt.Color(105, 151, 207));
        userInput.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        userInput.setForeground(new java.awt.Color(255, 255, 251));
        userInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userInput.setBorder(null);
        jPanel1.add(userInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 220, 47));

        userLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(24, 49, 85));
        userLabel.setText("Usuario");
        jPanel1.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        emailInput.setBackground(new java.awt.Color(105, 151, 207));
        emailInput.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        emailInput.setForeground(new java.awt.Color(255, 255, 251));
        emailInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailInput.setBorder(null);
        jPanel1.add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 220, 47));

        emailLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(24, 49, 85));
        emailLabel.setText("Correo Electrónico");
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        psswdLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18)); // NOI18N
        psswdLabel.setForeground(new java.awt.Color(24, 49, 85));
        psswdLabel.setText("Contraseña");
        jPanel1.add(psswdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        psswdInput.setBackground(new java.awt.Color(105, 151, 207));
        psswdInput.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        psswdInput.setForeground(new java.awt.Color(255, 255, 251));
        psswdInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        psswdInput.setBorder(null);
        psswdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psswdInputActionPerformed(evt);
            }
        });
        jPanel1.add(psswdInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 220, 47));

        rePsswdInput.setBackground(new java.awt.Color(105, 151, 207));
        rePsswdInput.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        rePsswdInput.setForeground(new java.awt.Color(255, 255, 251));
        rePsswdInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rePsswdInput.setBorder(null);
        rePsswdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rePsswdInputActionPerformed(evt);
            }
        });
        jPanel1.add(rePsswdInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 220, 47));

        rePsswdLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18)); // NOI18N
        rePsswdLabel.setForeground(new java.awt.Color(24, 49, 85));
        rePsswdLabel.setText("Confirmar Contraseña");
        jPanel1.add(rePsswdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        nextButton.setBackground(new java.awt.Color(105, 151, 207));
        nextButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        nextButton.setForeground(new java.awt.Color(255, 255, 251));
        nextButton.setText("⇢");
        nextButton.setBorder(null);
        jPanel1.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 47, 47));

        logIn.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        logIn.setForeground(new java.awt.Color(105, 151, 207));
        logIn.setText("Iniciar Sesión");
        logIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logInMouseClicked(evt);
            }
        });
        jPanel1.add(logIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgSignUp.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void psswdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psswdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psswdInputActionPerformed

    private void rePsswdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rePsswdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rePsswdInputActionPerformed

    private void logInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);   // Instancia la clase SingUp y llama a setVisible(true) para hacerse visible
        this.dispose();                   // Cierra la ventana actual en la que se hace clic
    }//GEN-LAST:event_logInMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logIn;
    private javax.swing.JButton nextButton;
    private javax.swing.JPasswordField psswdInput;
    private javax.swing.JLabel psswdLabel;
    private javax.swing.JPasswordField rePsswdInput;
    private javax.swing.JLabel rePsswdLabel;
    private javax.swing.JTextField userInput;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
