/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package academy;

/**
 *
 * @author U53R
 */
public class Topic extends javax.swing.JFrame {

    /**
     * Creates new form Topic
     */
    public Topic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        closeSessionLabel = new javax.swing.JLabel();
        profileLabel = new javax.swing.JLabel();
        prevButton1 = new javax.swing.JPanel();
        prevLabel1 = new javax.swing.JLabel();
        prevButton = new javax.swing.JPanel();
        prevLabel = new javax.swing.JLabel();
        circlesBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Academy");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(239, 246, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Rounded Mplus 1c ExtraBold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(119, 149, 203));
        jLabel2.setText("Estructura de Control");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N
        jPanel1.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, -1, 60));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(true);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(171, 225, 248));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(24, 49, 85));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Las estructuras de control son un concepto fundamental en la programación y se utilizan para controlar el flujo de ejecución de un programa. Hay tres tipos principales de estructuras de control:\n\nEstructuras de control secuenciales: Estas estructuras permiten que las instrucciones se ejecuten en secuencia, una después de la otra, en el orden en que aparecen en el programa. No involucran toma de decisiones ni bucles. Ejemplos de esto son las instrucciones simples que se ejecutan una tras otra.\n\nEstructuras de control de decisión: Estas estructuras se utilizan para tomar decisiones en un programa. Los condicionales, como las declaraciones \"if\" (si) y \"else\" (si no), permiten que el programa elija diferentes caminos de ejecución basados en condiciones específicas. Por ejemplo, puedes escribir un programa que realice una acción si se cumple una condición y otra acción si no se cumple.\n\nEstructuras de control de bucle: Estas estructuras se utilizan para repetir una serie de instrucciones múltiples veces. Los bucles, como \"for\" (para) y \"while\" (mientras), permiten que un bloque de código se ejecute repetidamente mientras se cumpla una condición. Esto es útil para automatizar tareas que deben realizarse varias veces.\n\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 840, 270));

        closeSessionLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        closeSessionLabel.setForeground(new java.awt.Color(105, 151, 207));
        closeSessionLabel.setText("Cerrar Sesión");
        closeSessionLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeSessionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeSessionLabelMouseClicked(evt);
            }
        });
        jPanel1.add(closeSessionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        profileLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 14)); // NOI18N
        profileLabel.setForeground(new java.awt.Color(105, 151, 207));
        profileLabel.setText("Mi Cuenta");
        profileLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileLabelMouseClicked(evt);
            }
        });
        jPanel1.add(profileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        prevButton1.setBackground(new java.awt.Color(105, 151, 207));
        prevButton1.setForeground(new java.awt.Color(255, 255, 251));
        prevButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prevButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prevButton1MouseClicked(evt);
            }
        });
        prevButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prevLabel1.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18)); // NOI18N
        prevLabel1.setForeground(new java.awt.Color(255, 255, 251));
        prevLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prevLabel1.setText("Ir al Test");
        prevButton1.add(prevLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jPanel1.add(prevButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 120, 47));

        prevButton.setBackground(new java.awt.Color(105, 151, 207));
        prevButton.setForeground(new java.awt.Color(255, 255, 251));
        prevButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prevButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prevButtonMouseClicked(evt);
            }
        });
        prevButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prevLabel.setFont(new java.awt.Font("Rounded Mplus 1c Medium", 0, 18)); // NOI18N
        prevLabel.setForeground(new java.awt.Color(255, 255, 251));
        prevLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prevLabel.setText("Contenido");
        prevButton.add(prevLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jPanel1.add(prevButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 120, 47));

        circlesBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgTopic.png"))); // NOI18N
        jPanel1.add(circlesBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeSessionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeSessionLabelMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);   // Crea y muestra el login
        this.dispose();                   // Cierra la ventana actual
    }//GEN-LAST:event_closeSessionLabelMouseClicked

    private void profileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileLabelMouseClicked
        // TODO add your handling code here:
        new Profile().setVisible(true);   // Instancia la clase Profile y llama a setVisible(true) para hacerse visible
        this.dispose();                     // Cierra la ventana actual en la que se hace clic
    }//GEN-LAST:event_profileLabelMouseClicked

    private void prevButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevButtonMouseClicked
        // TODO add your handling code here:
        new Content().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prevButtonMouseClicked

    private void prevButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevButton1MouseClicked
        // TODO add your handling code here:
        new Test().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prevButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Topic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Topic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Topic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Topic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Topic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel circlesBg;
    private javax.swing.JLabel closeSessionLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel prevButton;
    private javax.swing.JPanel prevButton1;
    private javax.swing.JLabel prevLabel;
    private javax.swing.JLabel prevLabel1;
    private javax.swing.JLabel profileLabel;
    // End of variables declaration//GEN-END:variables
}
